# Generated by scripts/homebrew-cask.sh from the v0.44.1 release. Do not edit by
# hand: the next release overwrites it, and a hand-edited sha256 that no longer
# matches its URL fails at install time on someone else's machine.
#
# QUARANTINE. The postflight below clears com.apple.quarantine from the bundle
# Homebrew just staged. This app is ad-hoc signed and NOT notarized, so with
# the flag left in place macOS refuses to launch it and the user is sent to
# System Settings to override Gatekeeper by hand — an install that has not
# installed.
#
# What that gives up, and what stands in for it: Gatekeeper answers "did these
# bytes come from a known party, unmodified". Here that answer comes from the
# sha256 below instead — pinned in a tap the user chose to add, fetched over
# HTTPS from a Release built by CI. It is a different chain of trust rather
# than an absent one, but it IS weaker than notarization, and it is why this
# cask can live in this tap and nowhere else.
#
# When Developer ID signing and notarization land, the postflight block is
# deleted and nothing else in this file changes.
cask "agenthub-gui" do
  version "0.44.1,9614043"
  sha256 "2c9a995b83e974cded2908e9a2228228960878e3eb62d6f6188bc8331d0899cb"

  url "https://github.com/dinstein/agent-hub/releases/download/v#{version.csv.first}/" \
      "AgentHub-#{version.csv.first}-#{version.csv.second}-macos-universal.dmg"
  name "AgentHub"
  desc "Local gateway between AI clients and MCP servers"
  homepage "https://github.com/dinstein/agent-hub"

  # The tap is regenerated by the release that publishes the DMG, so this
  # block buys no freshness. It is here because `brew audit --online` runs a
  # livecheck whether or not one is declared, and the default it infers reads
  # the release TAG — "0.19.0", which can never equal a version carrying a
  # build id. Left out, the audit fails on every release, and a check that is
  # always red is one nobody reads. Reading the asset names instead answers in
  # the same shape the version is written in.
  livecheck do
    url :url
    strategy :github_latest do |json|
      json["assets"]&.map do |asset|
        match = asset["name"]&.match(/^AgentHub-(\d+(?:\.\d+)+)-(\h+)-macos-universal\.dmg$/i)
        next if match.blank?

        "#{match[1]},#{match[2]}"
      end
    end
  end

  # A bare symbol is "this release or newer" — the upper bound has its own
  # stanza (maximum_macos), and `brew style` rewrites ">= :big_sur" to this.
  depends_on macos: :big_sur # = the bundle's LSMinimumSystemVersion 11.0
  # The CLI. Installing the GUI installs it; $PATH's agenthub then has exactly
  # one owner, which the app bundle's private copy deliberately is not.
  depends_on formula: "dinstein/agenthub/agenthub"

  app "AgentHub.app"

  postflight do
    # -c rather than -d com.apple.quarantine: -d fails on a file that does not
    # carry the attribute, and a recursive pass over a bundle meets plenty.
    system_command "/usr/bin/xattr", args: ["-c", "-r", "#{appdir}/AgentHub.app"]
  end

  # The app is not the only process it starts. A daemon launched from inside
  # the bundle would outlive an uninstall holding a deleted binary; stopping it
  # is safe because the next call starts one again (api.DialOrStart), from the
  # formula's copy this time.
  #
  # Run through /bin/sh, not the bundled binary directly: by the time someone
  # uninstalls, the .app may already have been dragged to the Trash by hand,
  # and an uninstall stanza that cannot find its executable is not a thing to
  # gamble a user's uninstall on. must_succeed: false covers the rest — there
  # may be no daemon running, and that is not a failed uninstall.
  uninstall quit:   "com.dinstein.agenthub",
            script: {
              executable:   "/bin/sh",
              args:         ["-c", "'#{appdir}/AgentHub.app/Contents/MacOS/agenthub' daemon stop >/dev/null 2>&1"],
              must_succeed: false,
            }

  # The release channel's directory only. A machine that also ran development
  # builds has an AgentHubDev beside it, which belongs to a checkout rather
  # than to this package — zapping it would delete someone's working state on
  # the strength of an uninstall they meant for the app.
  zap trash: "~/Library/Application Support/AgentHub"

  caveats <<~EOS
    The app is ad-hoc signed but not notarized, so this cask cleared the
    quarantine flag macOS puts on downloads; it is the pinned sha256 above,
    not Gatekeeper, that vouches for the bytes.

    Credentials kept in the macOS keychain survive `brew uninstall --zap`.
    Remove them from Keychain Access if you want them gone.
  EOS
end
