# Generated by scripts/homebrew-formula.sh from the v0.9.0 release. Do not edit
# by hand: the next release overwrites it, and a hand-edited sha256 that no
# longer matches its URL fails at install time on someone else's machine.
class Agenthub < Formula
  desc "Local gateway between AI clients and MCP servers"
  homepage "https://github.com/dinstein/homebrew-agenthub"
  version "0.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dinstein/homebrew-agenthub/releases/download/v0.9.0/agenthub-0.9.0-250aa62-darwin-arm64.tar.gz"
      sha256 "bdc1c76b71eafb51324c040947a89f70072551c4a5b7786eb0de52b7812da825"
    end
    on_intel do
      url "https://github.com/dinstein/homebrew-agenthub/releases/download/v0.9.0/agenthub-0.9.0-250aa62-darwin-amd64.tar.gz"
      sha256 "e6caed237cddb63978e4ff801886ef787d355cbc0e7ac1028b36c50823270bd3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dinstein/homebrew-agenthub/releases/download/v0.9.0/agenthub-0.9.0-250aa62-linux-arm64.tar.gz"
      sha256 "3537fb531587b36035652954ed0f77ec21fbfa8517402676149ce772e0d01cd7"
    end
    on_intel do
      url "https://github.com/dinstein/homebrew-agenthub/releases/download/v0.9.0/agenthub-0.9.0-250aa62-linux-amd64.tar.gz"
      sha256 "821e4b6f5e2c56c897c084c3ffb45160fe2593989c287e7dcd0a6275c54e0eff"
    end
  end

  def install
    bin.install "agenthub"
  end

  def caveats
    <<~EOS
      Add a downstream MCP server, then point an AI client at the gateway
      (that second step edits the client's own config, so look at it first):

        agenthub server add linear --url https://mcp.linear.app/mcp
        agenthub server test linear

        agenthub client detect
        agenthub client connect claude-code --dry-run
        agenthub client connect claude-code

      Then restart the client. Servers added later need no further client
      changes — that is the point of the gateway.

      By default a client sees every enabled server. To show it less, put the
      narrowing in a profile and bind the client to it — rebinding takes
      effect on a running session, no restart:

        agenthub profile create research
        agenthub profile server add research linear
        agenthub client bind claude-code research
    EOS
  end

  test do
    out = shell_output("#{bin}/agenthub --version")
    assert_match version.to_s, out

    # A release build must NOT be a dev build. The channel is a link-time flag,
    # so the only way to be sure the shipped artifact resolves the real data
    # directory is to ask the binary. Getting this wrong is silent: the user
    # keeps their config in AgentHubDev and reports that everything vanished.
    refute_match "(dev)", out

    # Exit 4 is "daemon offline", the correct answer on a machine that has
    # never started one. shell_output asserts the status itself, so this
    # proves the binary runs and classifies rather than only printing a
    # version string.
    shell_output("#{bin}/agenthub daemon status", 4)
  end
end
