# Generated by scripts/homebrew-formula.sh from the v0.28.0 release. Do not edit
# by hand: the next release overwrites it, and a hand-edited sha256 that no
# longer matches its URL fails at install time on someone else's machine.
class Agenthub < Formula
  desc "Local gateway between AI clients and MCP servers"
  homepage "https://github.com/dinstein/agent-hub"
  version "0.28.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dinstein/agent-hub/releases/download/v0.28.0/agenthub-0.28.0-b3b947e-darwin-arm64.tar.gz"
      sha256 "933d2e7ea0038dafbb21e066402c3fea0e55b7289f9fe83e8090ba6a51ffea3a"
    end
    on_intel do
      url "https://github.com/dinstein/agent-hub/releases/download/v0.28.0/agenthub-0.28.0-b3b947e-darwin-amd64.tar.gz"
      sha256 "05f096e731f706ad0ccfce84a389872f5bdb1d1ef8047a1602358f6e36c94b21"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dinstein/agent-hub/releases/download/v0.28.0/agenthub-0.28.0-b3b947e-linux-arm64.tar.gz"
      sha256 "fd77591a5bc1d2b81ac885d33d718b3e2db579e210f7526712d80cee5324a1ea"
    end
    on_intel do
      url "https://github.com/dinstein/agent-hub/releases/download/v0.28.0/agenthub-0.28.0-b3b947e-linux-amd64.tar.gz"
      sha256 "6f2a981d0d6445861e440763b0f560e92b9cc72706b55c732a751ded9360fcdb"
    end
  end

  def install
    bin.install "agenthub"
  end

  def caveats
    <<~EOS
      Add a downstream MCP server, switch it on, then point an AI client at the
      gateway (that last step edits the client's own config, so look at it first):

        agenthub server add linear --url https://mcp.linear.app/mcp
        agenthub auth login linear     # signs in, and switches the server on
        agenthub server test linear

      'add' only writes the definition down: the entry stays off until something
      puts it into service. For a server that needs no account, that second line
      is 'agenthub server enable <id>' instead of the login.

        agenthub client detect
        agenthub client connect claude-code --dry-run
        agenthub client connect claude-code

      Then restart the client. Servers added later need no further client
      changes — that is the point of the gateway.

      By default a client sees every enabled server. To show it less, put the
      narrowing in a profile and bind the client to it — rebinding takes
      effect on a running session, no restart:

        agenthub profile create research
        agenthub profile server add research linear
        agenthub client bind claude-code research
    EOS
  end

  test do
    out = shell_output("#{bin}/agenthub --version")
    assert_match version.to_s, out

    # A release build must NOT be a dev build. The channel is a link-time flag,
    # so the only way to be sure the shipped artifact resolves the real data
    # directory is to ask the binary. Getting this wrong is silent: the user
    # keeps their config in AgentHubDev and reports that everything vanished.
    refute_match "(dev)", out

    # Exit 4 is "daemon offline", the correct answer on a machine that has
    # never started one. shell_output asserts the status itself, so this
    # proves the binary runs and classifies rather than only printing a
    # version string.
    shell_output("#{bin}/agenthub daemon status", 4)
  end
end
