# Generated by scripts/homebrew-formula.sh from the v0.27.0 release. Do not edit
# by hand: the next release overwrites it, and a hand-edited sha256 that no
# longer matches its URL fails at install time on someone else's machine.
class Agenthub < Formula
  desc "Local gateway between AI clients and MCP servers"
  homepage "https://github.com/dinstein/agent-hub"
  version "0.27.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dinstein/agent-hub/releases/download/v0.27.0/agenthub-0.27.0-39e8ad8-darwin-arm64.tar.gz"
      sha256 "a783df3c5fab638ba734ad73a9b7f9c5470720c857fa9628deecd761ba23a8d7"
    end
    on_intel do
      url "https://github.com/dinstein/agent-hub/releases/download/v0.27.0/agenthub-0.27.0-39e8ad8-darwin-amd64.tar.gz"
      sha256 "4b3b48d0e78b5c56991f0cdb255fdc8eaee5b46ed3ad4ebce818b86c4ef7eb27"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dinstein/agent-hub/releases/download/v0.27.0/agenthub-0.27.0-39e8ad8-linux-arm64.tar.gz"
      sha256 "a08bba02fb3dd791fe10446839eea68d9f521a847ebf01ea5bd858077202dc6a"
    end
    on_intel do
      url "https://github.com/dinstein/agent-hub/releases/download/v0.27.0/agenthub-0.27.0-39e8ad8-linux-amd64.tar.gz"
      sha256 "f56ad24a9730b00c4f968eb33e156eabf245f2fd766215a4b6f8a510a46865fc"
    end
  end

  def install
    bin.install "agenthub"
  end

  def caveats
    <<~EOS
      Add a downstream MCP server, switch it on, then point an AI client at the
      gateway (that last step edits the client's own config, so look at it first):

        agenthub server add linear --url https://mcp.linear.app/mcp
        agenthub auth login linear     # signs in, and switches the server on
        agenthub server test linear

      'add' only writes the definition down: the entry stays off until something
      puts it into service. For a server that needs no account, that second line
      is 'agenthub server enable <id>' instead of the login.

        agenthub client detect
        agenthub client connect claude-code --dry-run
        agenthub client connect claude-code

      Then restart the client. Servers added later need no further client
      changes — that is the point of the gateway.

      By default a client sees every enabled server. To show it less, put the
      narrowing in a profile and bind the client to it — rebinding takes
      effect on a running session, no restart:

        agenthub profile create research
        agenthub profile server add research linear
        agenthub client bind claude-code research
    EOS
  end

  test do
    out = shell_output("#{bin}/agenthub --version")
    assert_match version.to_s, out

    # A release build must NOT be a dev build. The channel is a link-time flag,
    # so the only way to be sure the shipped artifact resolves the real data
    # directory is to ask the binary. Getting this wrong is silent: the user
    # keeps their config in AgentHubDev and reports that everything vanished.
    refute_match "(dev)", out

    # Exit 4 is "daemon offline", the correct answer on a machine that has
    # never started one. shell_output asserts the status itself, so this
    # proves the binary runs and classifies rather than only printing a
    # version string.
    shell_output("#{bin}/agenthub daemon status", 4)
  end
end
